import { motion } from "motion/react";
import { MessageSquareText, ShieldCheck } from "lucide-react";

export function Slide19_AgenticEra() {
  return (
    <div className="flex h-screen w-full bg-black text-white p-12 md:p-24 overflow-hidden relative items-center">
      
      {/* Background Ambience */}
      <div className="absolute inset-0 z-0">
         <img 
            src="https://images.unsplash.com/photo-1767473281200-0b1815c30bfa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGZsb3dpbmclMjBjb252ZXJzYXRpb25hbCUyMGFpfGVufDF8fHx8MTc3NDQ2MjQ5MXww&ixlib=rb-4.1.0&q=80&w=1080" 
            alt="Flowing conversational AI" 
            className="w-full h-full object-cover mix-blend-luminosity opacity-20 scale-110"
         />
         <div className="absolute inset-0 bg-gradient-to-t from-black via-black/80 to-transparent" />
      </div>

      <div className="z-10 flex w-full flex-col h-full max-w-6xl mx-auto justify-center mt-12">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center w-full max-w-4xl mx-auto mb-16"
        >
          <h2 className="text-6xl md:text-[80px] font-['Bebas_Neue',sans-serif] uppercase tracking-wider mb-8 leading-[0.9] text-white">
            Designing for <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 to-red-500">Autonomous Agents</span>
          </h2>
          <p className="slide-description">
            We are shifting from Point-and-Click graphical interfaces (GUI) to Intent-Based conversational and agentic interfaces. Users state what they want, and the AI figures out how to execute it.
          </p>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.3 }}
          className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full"
        >
          <div className="bg-zinc-900/60 border border-zinc-800 p-8 rounded-3xl backdrop-blur-md">
            <h3 className="text-3xl font-['Bebas_Neue',sans-serif] uppercase tracking-wide text-zinc-100 mb-4">
              Invisible Logic
            </h3>
            <p className="slide-description">
              If the UI is generated by AI, the designer's job is to craft the invisible "rules of engagement." How does the agent ask for clarification? How does it handle errors?
            </p>
          </div>

          <div className="bg-zinc-900/60 border border-zinc-800 p-8 rounded-3xl backdrop-blur-md">

            <h3 className="text-3xl font-['Bebas_Neue',sans-serif] uppercase tracking-wide text-zinc-100 mb-4">
              Trust & Transparency
            </h3>
            <p className="slide-description">
              When agents take actions on a user's behalf, trust is paramount. Design must focus on making the AI's logic transparent, reversible, and explicitly clear.
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}